apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend

---
kind: Pod
apiVersion: v1
metadata:
  name: backend
  labels:
    app: backend
spec:
  serviceAccountName: backend
  containers:
    - name: whoami
      image: jspdown/whoamitcp:demo-proxy-protocol
      imagePullPolicy: IfNotPresent
      args:
        - "-proxyprotocol=true"

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: backend
      protocol: TCP
  selector:
    app: backend

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: backend
spec:
  entryPoints:
    - proxy
  routes:
  - match: HostSNI(`*`)
    services:
    - name: backend
      port: 8080
      proxyProtocol: 
        version: 1

