apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller

---
kind: Pod
apiVersion: v1
metadata:
  name: traefik
  labels:
    app: traefik-lb
spec:
  serviceAccountName: traefik-ingress-controller
  containers:
    - name: traefik
      image: traefik:v2.4.0
      imagePullPolicy: IfNotPresent
      args:
        - --api.insecure
        - --log.level=debug
        - --entrypoints.proxy.address=:9000
        - --entrypoints.proxy.proxyprotocol.insecure=true
        - --providers.kubernetescrd
      ports:
        - name: proxy
          containerPort: 9000
        - name: api
          containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  selector:
    app: traefik-lb
  ports:
    - protocol: TCP
      port: 9000
      targetPort: proxy
      name: proxy
    - protocol: TCP
      port: 8080
      targetPort: api
      name: api
  type: LoadBalancer

